### ISSUE TITLE
New instanced logic doesn't work on OSX

### ISSUE THREAD

**Issue by Rhuagh** [alexheretic/gfx-glyph#26]
It is using GL functions that aren't available on OSX:

```
thread 'main' panicked at 'gl function was not loaded', /Users/simon/projects/private/gfx-glyph/target/debug/build/gfx_gl-3c9b310b6cadffc7/out/gl_bindings.rs:1506:13
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:207
   3: std::panicking::default_hook
             at libstd/panicking.rs:223
   4: std::panicking::begin_panic
             at libstd/panicking.rs:402
   5: std::panicking::begin_panic
             at /Users/travis/build/rust-lang/rust/src/libstd/panicking.rs:365
   6: gfx_gl::missing_fn_panic
             at ./target/debug/build/gfx_gl-3c9b310b6cadffc7/out/gl_bindings.rs:1506
   7: gfx_gl::Gl::DrawArraysInstancedBaseInstance
             at ./target/debug/build/gfx_gl-3c9b310b6cadffc7/out/gl_bindings.rs:3573
   8: gfx_device_gl::Device::process
             at /Users/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.2/src/lib.rs:667
   9: gfx_device_gl::Device::no_fence_submit
             at /Users/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.2/src/lib.rs:815
  10: gfx_device_gl::Device::track_mapped_gpu_access
             at /Users/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx_device_gl-0.15.2/src/lib.rs:937
  11: <gfx::encoder::Encoder<R, C>>::flush_no_reset
             at /Users/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-0.17.1/src/encoder.rs:197
  12: <gfx::encoder::Encoder<R, C>>::flush
             at /Users/simon/.cargo/registry/src/github.com-1ecc6299db9ec823/gfx-0.17.1/src/encoder.rs:188
  13: varied::main
             at examples/varied.rs:151
  14: std::rt::lang_start::{{closure}}
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  15: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:306
  16: panic_unwind::dwarf::eh::read_encoded_pointer
             at libpanic_unwind/lib.rs:102
  17: <std::io::Write::write_fmt::Adaptor<'a, T> as core::fmt::Write>::write_str
             at libstd/panicking.rs:285
             at libstd/panic.rs:361
             at libstd/rt.rs:58
  18: std::rt::lang_start
             at /Users/travis/build/rust-lang/rust/src/libstd/rt.rs:74
  19: varied::main
```

I'm on High Sierra, 10.13.4.

**Comment by Rhuagh** [comment]
The geometry shader version works.

**Comment by kvark** [comment]
Iirc, GL backend erroneously calls that function instead of a simpler glDrawInstanced. Base instance is not really used by your code, right?

**Comment by alexheretic** [comment]
@kvark not explicitly used no. Is the backend fairly fixable in this regard, I've never delved? 

I'm going to see if I can get travis to tell me about this kind of failure via a render test

**Comment by alexheretic** [comment]
Ha travis is no help, the mac render test passed & the linux one failed due to missing mesa!

**Comment by alexheretic** [comment]
```rust
// gl backend lib.rs
...
Command::Draw(primitive, start, count, instances) => {
                let gl = &self.share.context;
                match instances {
                    Some((num, base)) if self.share.capabilities.instance_call_supported => unsafe {
                        gl.DrawArraysInstancedBaseInstance(
                            primitive,
                            start as gl::types::GLsizei,
                            count as gl::types::GLsizei,
                            num as gl::types::GLsizei,
                            base as gl::types::GLuint,
                        );
                    },
                    Some(_) => {
                        error!("Instanced draw calls are not supported");
                    },
                    None => unsafe {
                        gl.DrawArrays(
                            primitive,
                            start as gl::types::GLsizei,
                            count as gl::types::GLsizei
                        );
                    },
                }
},
...
```

**Comment by alexheretic** [comment]
I'll squint at the gl backend tomorrow, I can always revert to the geometry method.

Otherwise mac users can stay on `0.10` until this is fixed.

**Comment by Rhuagh** [comment]
Is winit updated in 0.10?

**Comment by alexheretic** [comment]
> Is winit updated in 0.10?

Winit isn't a dependency ;) just gfx & rusttype are hindered by gfx-glyph

**Comment by alexheretic** [comment]
Our usage is simple base-vertex 0, so we can use `glDrawArraysInstanced` supported by OpenGL 3.2. Awaiting https://github.com/gfx-rs/gfx/pull/2085 + release.

**Comment by kvark** [comment]
Sweet, thanks for the PR!

**Comment by alexheretic** [comment]
With `gfx_device_gl = "0.15.3"` this should be fixed, can you re-test @Rhuagh?

**Comment by Rhuagh** [comment]
Works now, yeah.

**Comment by kvark** [comment]
Sweet, thanks everyone!
